import Head from 'next/head'
import Hero from '../components/Hero'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>PCU Online Clearance System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <Features />
      <Footer />

      <Link href={'/students/home'}><h1>Student Account</h1></Link>
      <Link href={'/instructors/home'}><h1>Staff Account</h1></Link>
    </div>
  )
}
